### ISSUE TITLE
Upper bound on ipywidgets causing issues

### ISSUE THREAD

**Issue by consideRatio** [davidbrochart/ipyspin#4]
Hi @davidbrochart, thank you for your extensive work in open-source - your name pops up very often =)

## Problem description

I'm a user of https://github.com/pangeo-data/pangeo-docker-images and have traced a regression in a high level user experience of those images. They have `xarray_leaflet` installed in them, which in turn depends on `ipyspin`.

The regression observed is that `ipyspin` is detected by JupyterLab as in need of a rebuild and prompts users about it when their jupyterlab session starts. The reason that this shows now is that `ipyspin` 0.1.2 has been installed instead of the previosly installed version of 0.1.6. The reason ipyspin got downgraded is because 0.1.2 didn't have an upper bound constraint like `ipywidgets<8`, but 0.1.5 and 0.1.6 did, and now that  `ipywidgets=8` is used by other packages ipyspin got downgraded to a version that didn't make use of the excellent jupyterlab 3 extension packaging.

## Suggested resolution

Unless there is a known issue to resolve to use this package with ipywidgets 8, I suggest the upper bound is entirely removed as compared to just bumped to version 9. I suggest that because it my experience so far in the Python ecosystem is that precautionary upper bounds often cause more maintenance effort for maintainers and often cause more problem than benefits for end users.

Cheers from Sweden
/ Erik

**Comment by consideRatio** [comment]
This is off topic, but I'd like to advocate that the new release is versioned 1.0.0 rather than 0.1.7 - but its entirely off topic.

I find that many projects would benefit from going to 1.0.0 as soon as they have passed a flurry of initial changes and gained a few users or dependent projects.

I'm influenced greatly by reading on https://semver.org, where they suggest one should quickly arrive at 1.0.0. Here is experpt from the section of [**How do I know when to release 1.0.0?**](https://semver.org/#how-do-i-know-when-to-release-100).

> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

**Comment by davidbrochart** [comment]
Thanks @consideRatio, I released version `1.0.1`, let me know if this solves your issue!

**Comment by consideRatio** [comment]
I'm confident it will as soon as its packaged in conda-forge, if not I'll follow up!

Thank you @davidbrochart!!!

**Comment by consideRatio** [comment]
Issue confirmed to be resolved, thank you @davidbrochart!

**Comment by davidbrochart** [comment]
Great, thanks for the feedback!
