### ISSUE TITLE
Trying ipyspin via Binder fails with dependency resolution error

### ISSUE THREAD

**Issue by tylere** [davidbrochart/ipyspin#5]
# Description

Trying out ipyspin via Binder (at commit [d52cf4f](https://github.com/davidbrochart/ipyspin/commit/d52cf4f0cf40e8955fd37bb124576debff87cb8e)) results in a Binder build error.

# To replicate
- Open https://mybinder.org/v2/gh/davidbrochart/ipyspin/master?filepath=examples%2Fintroduction.ipynb

# Binder build log
<pre>
Waiting for build to start...
Picked Git content provider.
Cloning into '/tmp/repo2docker1m7xb15i'...
HEAD is now at d52cf4f v1.0.1
Building conda environment for python=3.10
Using PythonBuildPack builder
Building conda environment for python=3.10
Building conda environment for python=3.10
Step 1/49 : FROM buildpack-deps:bionic
 ---> 2d0dfd868824
Step 2/49 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> 4fce3a7216a0
Step 3/49 : RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends locales > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 142a6247b79e
Step 4/49 : RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen &&     locale-gen
 ---> Using cache
 ---> 0c5348293fd8
Step 5/49 : ENV LC_ALL=en_US.UTF-8     LANG=en_US.UTF-8     LANGUAGE=en_US.UTF-8
 ---> Using cache
 ---> a87595781a12
Step 6/49 : ENV SHELL=/bin/bash
 ---> Using cache
 ---> 2fca4d85ab35
Step 7/49 : ARG NB_USER
 ---> Using cache
 ---> 29b3000a3e2b
Step 8/49 : ARG NB_UID
 ---> Using cache
 ---> 6c33474d3ac5
Step 9/49 : ENV USER=${NB_USER}     HOME=/home/${NB_USER}
 ---> Using cache
 ---> 1b706eb4a132
Step 10/49 : RUN groupadd         --gid ${NB_UID}         ${NB_USER} &&     useradd         --comment "Default user"         --create-home         --gid ${NB_UID}         --no-log-init         --shell /bin/bash         --uid ${NB_UID}         ${NB_USER}
 ---> Using cache
 ---> 2120650ed740
Step 11/49 : RUN apt-get -qq update &&     apt-get -qq install --yes --no-install-recommends        less        unzip        > /dev/null &&     apt-get -qq purge &&     apt-get -qq clean &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> c2d8978d61ae
Step 12/49 : EXPOSE 8888
 ---> Using cache
 ---> 958f73bc738d
Step 13/49 : ENV APP_BASE=/srv
 ---> Using cache
 ---> 4d6924538641
Step 14/49 : ENV CONDA_DIR=${APP_BASE}/conda
 ---> Using cache
 ---> aec14e262e86
Step 15/49 : ENV NB_PYTHON_PREFIX=${CONDA_DIR}/envs/notebook
 ---> Using cache
 ---> 16cfe3e2dfd7
Step 16/49 : ENV NPM_DIR=${APP_BASE}/npm
 ---> Using cache
 ---> 722474257929
Step 17/49 : ENV NPM_CONFIG_GLOBALCONFIG=${NPM_DIR}/npmrc
 ---> Using cache
 ---> 2f39b3dc083e
Step 18/49 : ENV NB_ENVIRONMENT_FILE=/tmp/env/environment.lock
 ---> Using cache
 ---> d5b9fb8eff0d
Step 19/49 : ENV MAMBA_ROOT_PREFIX=${CONDA_DIR}
 ---> Using cache
 ---> 4444a4e1e308
Step 20/49 : ENV MAMBA_EXE=${CONDA_DIR}/bin/mamba
 ---> Using cache
 ---> dcf55ac10d7c
Step 21/49 : ENV CONDA_PLATFORM=linux-64
 ---> Using cache
 ---> 114f68a0abdf
Step 22/49 : ENV KERNEL_PYTHON_PREFIX=${NB_PYTHON_PREFIX}
 ---> Using cache
 ---> 02062cb0ca68
Step 23/49 : ENV PATH=${NB_PYTHON_PREFIX}/bin:${CONDA_DIR}/bin:${NPM_DIR}/bin:${PATH}
 ---> Using cache
 ---> 38623cb9f4e3
Step 24/49 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e10-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2factivate-2dconda-2esh-44e764 /etc/profile.d/activate-conda.sh
 ---> Using cache
 ---> 1a9dbc861b00
Step 25/49 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e10-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2fenvironment-2epy-2d3-2e10-2dlinux-2d64-2elock-388e0b /tmp/env/environment.lock
 ---> Using cache
 ---> abd0f3f32350
Step 26/49 : COPY --chown=1000:1000 build_script_files/-2fusr-2flib-2fpython3-2e10-2fsite-2dpackages-2frepo2docker-2fbuildpacks-2fconda-2finstall-2dbase-2denv-2ebash-e5509f /tmp/install-base-env.bash
 ---> Using cache
 ---> c00f76ee4eb9
Step 27/49 : RUN TIMEFORMAT='time: %3R' bash -c 'time /tmp/install-base-env.bash' && rm -rf /tmp/install-base-env.bash /tmp/env
 ---> Using cache
 ---> b99ed3721fa8
Step 28/49 : RUN mkdir -p ${NPM_DIR} && chown -R ${NB_USER}:${NB_USER} ${NPM_DIR}
 ---> Using cache
 ---> ceb147c3029f
Step 29/49 : USER root
 ---> Using cache
 ---> 7ebbf548c5cd
Step 30/49 : ARG REPO_DIR=${HOME}
 ---> Using cache
 ---> c75341bfe3e1
Step 31/49 : ENV REPO_DIR=${REPO_DIR}
 ---> Using cache
 ---> 36002c8b0293
Step 32/49 : RUN if [ ! -d "${REPO_DIR}" ]; then         /usr/bin/install -o ${NB_USER} -g ${NB_USER} -d "${REPO_DIR}";     fi
 ---> Using cache
 ---> 1fa9376d9fa9
Step 33/49 : WORKDIR ${REPO_DIR}
 ---> Using cache
 ---> 271081ebf6cc
Step 34/49 : RUN chown ${NB_USER}:${NB_USER} ${REPO_DIR}
 ---> Using cache
 ---> 3384ca0aa64f
Step 35/49 : ENV PATH=${HOME}/.local/bin:${REPO_DIR}/.local/bin:${PATH}
 ---> Using cache
 ---> d11d94250914
Step 36/49 : ENV CONDA_DEFAULT_ENV=${KERNEL_PYTHON_PREFIX}
 ---> Using cache
 ---> ef0a574ed657
Step 37/49 : USER root
 ---> Using cache
 ---> 5e3b01dc6cfe
Step 38/49 : COPY --chown=1000:1000 src/ ${REPO_DIR}/
 ---> 71413667773b
Step 39/49 : USER ${NB_USER}
 ---> Running in 013a742df507
Removing intermediate container 013a742df507
 ---> 693cb7c09093
Step 40/49 : RUN ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir .
 ---> Running in 967f5f093335
Processing /home/jovyan
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: ipywidgets<9,>=7.6.0 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipyspin==1.0.1) (8.0.2)
Requirement already satisfied: ipython>=6.1.0 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (8.9.0)
Requirement already satisfied: traitlets>=4.3.1 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (5.9.0)
Requirement already satisfied: ipykernel>=4.5.1 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (6.21.1)
Requirement already satisfied: widgetsnbextension~=4.0 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (4.0.5)
Requirement already satisfied: jupyterlab-widgets~=3.0 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (3.0.5)
Requirement already satisfied: matplotlib-inline>=0.1 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (0.1.6)
Requirement already satisfied: psutil in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (5.9.4)
Requirement already satisfied: tornado>=6.1 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (6.2)
Requirement already satisfied: nest-asyncio in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (1.5.6)
Requirement already satisfied: debugpy>=1.6.5 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (1.6.6)
Requirement already satisfied: pyzmq>=17 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (25.0.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (8.0.2)
Requirement already satisfied: comm>=0.1.1 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (0.1.2)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (5.2.0)
Requirement already satisfied: packaging in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (23.0)
Requirement already satisfied: stack-data in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (0.6.2)
Requirement already satisfied: decorator in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (0.18.2)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.30 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (3.0.36)
Requirement already satisfied: pygments>=2.4.0 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (2.14.0)
Requirement already satisfied: pickleshare in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (0.7.5)
Requirement already satisfied: backcall in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (0.2.0)
Requirement already satisfied: pexpect>4.3 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (4.8.0)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (0.8.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (2.8.2)
Requirement already satisfied: platformdirs>=2.5 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel>=4.5.1->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (2.6.2)
Requirement already satisfied: ptyprocess>=0.5 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (0.7.0)
Requirement already satisfied: wcwidth in /srv/conda/envs/notebook/lib/python3.10/site-packages (from prompt-toolkit<3.1.0,>=3.0.30->ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (0.2.6)
Requirement already satisfied: asttokens>=2.1.0 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (2.2.1)
Requirement already satisfied: pure-eval in /srv/conda/envs/notebook/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (0.2.2)
Requirement already satisfied: executing>=1.2.0 in /srv/conda/envs/notebook/lib/python3.10/site-packages (from stack-data->ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (1.2.0)
Requirement already satisfied: six in /srv/conda/envs/notebook/lib/python3.10/site-packages (from asttokens>=2.1.0->stack-data->ipython>=6.1.0->ipywidgets<9,>=7.6.0->ipyspin==1.0.1) (1.16.0)
Building wheels for collected packages: ipyspin
  Building wheel for ipyspin (pyproject.toml): started
  Building wheel for ipyspin (pyproject.toml): finished with status 'error'
[91m  error: subprocess-exited-with-error
  
  Ã— Building wheel for ipyspin (pyproject.toml) did not run successfully.
  â”‚ exit code: 1
  â•°â”€> [79 lines of output]
      /tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/setuptools/dist.py:788: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      /tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/setuptools/config/setupcfg.py:516: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running bdist_wheel
      running jsdeps
      Installing build dependencies with npm.  This may take a while...
      > npm install
      npm notice
      npm notice New major version of npm available! 8.19.2 -> 9.6.1
      npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.1>
      npm notice Run `npm install -g npm@9.6.1` to update!
      npm notice
      npm ERR! code ERESOLVE
      npm ERR! ERESOLVE unable to resolve dependency tree
      npm ERR!
      npm ERR! While resolving: ipyspin@1.0.0
      npm ERR! Found: webpack@5.76.1
      npm ERR! node_modules/webpack
      npm ERR!   dev webpack@"^5" from the root project
      npm ERR!
      npm ERR! Could not resolve dependency:
      npm ERR! peer webpack@"4.x.x" from webpack-cli@3.3.12
      npm ERR! node_modules/webpack-cli
      npm ERR!   dev webpack-cli@"^3.1.2" from the root project
      npm ERR!
      npm ERR! Fix the upstream dependency conflict, or retry
      npm ERR! this command with --force, or --legacy-peer-deps
      npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
      npm ERR!
      npm ERR! See /home/jovyan/.npm/eresolve-report.txt for a full report.
      
      npm ERR! A complete log of this run can be found in:
      npm ERR!     /home/jovyan/.npm/_logs/2023-03-12T16_51_24_685Z-debug-0.log
      Traceback (most recent call last):
        File "/srv/conda/envs/notebook/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/srv/conda/envs/notebook/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/srv/conda/envs/notebook/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 91, in <module>
        File "/tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/jupyter_packaging/setupbase.py", line 503, in run
          [self.run_command(cmd) for cmd in cmds]
        File "/tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/jupyter_packaging/setupbase.py", line 503, in <listcomp>
          [self.run_command(cmd) for cmd in cmds]
        File "/tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/jupyter_packaging/setupbase.py", line 274, in run
          c.run()
        File "/tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/jupyter_packaging/setupbase.py", line 379, in run
          run(npm_cmd + ['install'], cwd=node_package)
        File "/tmp/pip-build-env-kuwe95vn/overlay/lib/python3.10/site-packages/jupyter_packaging/setupbase.py", line 225, in run
          return subprocess.check_call(cmd, **kwargs)
        File "/srv/conda/envs/notebook/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/srv/conda/envs/notebook/bin/npm', 'install']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
[0m[91m  ERROR: Failed building wheel for ipyspin
[0mFailed to build ipyspin
[91mERROR: Could not build wheels for ipyspin, which is required to install pyproject.toml-based projects
[0mRemoving intermediate container 967f5f093335
The command '/bin/sh -c ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir .' returned a non-zero code: 1
</pre>

**Comment by davidbrochart** [comment]
Thanks for reporting @tylere! It should be fixed in https://github.com/davidbrochart/ipyspin/commit/6718298bd941ac02aa9a4ef562a2af0f659505e4.
